#include<global.c>

void printSquare (float leftx, float boty){
	moveXY(leftx,boty);
	moveXY(leftx+14,boty+0);
	moveXY(leftx+14,boty+14);
	moveXY(leftx,boty+14);
	moveXY(leftx,boty+1);
	moveXY(leftx+13,boty+1);
	moveXY(leftx+13,boty+13);
	moveXY(leftx+1,boty+13);
	moveXY(leftx+1,boty+2);
	moveXY(leftx+12,boty+2);
	moveXY(leftx+12,boty+3);
	moveXY(leftx+2,boty+3);
	moveXY(leftx+2,boty+4);
	moveXY(leftx+12,boty+4);
	moveXY(leftx+12,boty+5);
	moveXY(leftx+2,boty+5);
	moveXY(leftx+2,boty+6);
	moveXY(leftx+12,boty+6);
	moveXY(leftx+12,boty+7);
	moveXY(leftx+2,boty+7);
	moveXY(leftx+2,boty+8);
	moveXY(leftx+12,boty+8);
	moveXY(leftx+12,boty+9);
	moveXY(leftx+2,boty+9);
	moveXY(leftx+2,boty+10);
	moveXY(leftx+12,boty+10);
	moveXY(leftx+12,boty+11);
	moveXY(leftx+2,boty+11);
	moveXY(leftx+2,boty+12);
	moveXY(leftx+12,boty+12);
}
